import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "@/context/AuthContext";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Nav";
import "react-toastify/dist/ReactToastify.css";

import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>
                    <div
                        style={{
                            height: "100vh",
                            width: "100%",
                            display: "flex",
                            flexDirection: "column",
                        }}
                    >
                        <Navbar />
                        {children}
                    </div>

                    <ToastContainer />
                </AuthProvider>
            </body>
        </html>
    );
}
